- README.md
- docs/available_plugins.md
Updated readme's and instructions based on new features in GI and new plugins.
> Updates to readme's for new plugins

- CONTRIBUTING.md
- README.md
- adds instructions for plug-in developers, how to push from their already existing repository to this repository. 
Signed-off-by: Tal Daniel <taldan@il.ibm.com>
> edit README.md with how to pull request

- .github/CODEOWNERS
Signed-off-by: Ofer-Haim <ofer.haim@ibm.com>
> updated code owners for UC

- filter-plugin/logstash-filter-generic-guardium/README.md
- filter-plugin/logstash-filter-hdfs-guardium/README.md
- filter-plugin/logstash-filter-mongodb-guardium/README.md
- filter-plugin/logstash-filter-mysql-aws-guardium/README.md
- filter-plugin/logstash-filter-mysql-percona-guardium/README.md
- filter-plugin/logstash-filter-pubsub-mysql-guardium/README.md
- filter-plugin/logstash-filter-pubsub-postgresql-guardium/README.md
- filter-plugin/logstash-filter-s3-guardium/README.md
For every plugin's readme, added a note about the "type" field: "The "type" fields should match in the input and the filter configuration sections. This field should be unique for every individual connector added."
> GRD-66851 - documentation update:

- filter-plugin/logstash-filter-generic-guardium/README.md
Add learning academy video URL
Signed-off-by: Joshua Klahn <klahn@us.ibm.com>
> Add learning academy training url for building filter plugins

- filter-plugin/logstash-filter-azure-apachesolr-guardium/ApacheSolrOverFilebeatPackage/AzureSolr/manifest.json
changes in menifest.json file for plugin version and data source supported version
> Updated Apache Solr GI packaging 

- filter-plugin/logstash-filter-onPremPostgres-guardium/EDBPostgres_README.md
- filter-plugin/logstash-filter-onPremPostgres-guardium/FEPostgres_README.md
- filter-plugin/logstash-filter-postgres-guardium/AuroraPostgres_README.md
- filter-plugin/logstash-filter-postgres-guardium/AwsPostgres_README.md
fixed broken URL in PostgreSQL readme files
> PostgreSQL readme files - fixed broken urls

- filter-plugin/logstash-filter-oua-guardium/README.md
> OUA UC - Readme updates

- filter-plugin/logstash-filter-oua-guardium/README.md
Signed-off-by: Alexa.Nahum <Alexa.Nahum@ibm.com>
> Update README.md- GRD-75215 OUA UC - Readme updates required

- filter-plugin/logstash-filter-redshift-aws-guardium/README.md
Change redshift plugin supported inputs to S3
> Redshift-doc: fixed supported inputs doc

- input-plugin/logstash-input-cloudwatch-logs/SettingsForRoleArn.md
Added instructions reg. role IAM settings
> Role arn doc

- filter-plugin/logstash-filter-documentdb-aws-guardium/build.gradle
- filter-plugin/logstash-filter-neptune-aws-guardium/build.gradle
- filter-plugin/logstash-filter-redshift-aws-guardium/build.gradle
Upgrade dependencies to resolve CVE-2022-45688, CVE-2023-2976, CVE-2023-5072
> INS-35925: resolves CVE-2022-45688, CVE-2023-2976, CVE-2023-5072

- filter-plugin/logstash-filter-pubsub-bigquery-guardium/src/main/java/com/ibm/guardium/bigquery/ApplicationConstants.java
moving changes from branch 1.5.1 to main .
> BigQueryUpdate

- filter-plugin/logstash-filter-mssql-guardium/AWSMSSQL_README.md
- filter-plugin/logstash-filter-mssql-guardium/GCPMSSQL_README.md
- filter-plugin/logstash-filter-mssql-guardium/MssqlOverJdbcPackage/gcpMSSQL.conf
- filter-plugin/logstash-filter-mssql-guardium/README.md
Publishing new UC MSSQL-GCP plugin with updated ReadMe.
> GCPMSSQLPublish

- filter-plugin/logstash-filter-dynamodb-guardium/dynamodbCloudtrail.conf
Modified the filter configurations to handle the authentication failed exceptions.
> GRD-78674 Modified the filter configurations to handle the authentication failed exceptions.

- input-plugin/logstash-input-mongo-atlas/README.md
- input-plugin/logstash-input-mongo-atlas/src/main/java/com/ibm/guardium/mongodb/MongoApi.java
[GRD-77625](https://jira-ds.rtp.raleigh.ibm.com:8443/browse/GRD-77625)
This PR includes fixes in Mongo Atlas input plugin.
> fix: GRD-77625 Mongo Atlas Input Plugin.

- filter-plugin/logstash-filter-pubsub-bigquery-guardium/README.md
Updating 'inclusion sink' filter for BigQuery.
> ReadMeUpdate- BigQuery

- input-plugin/logstash-input-mongo-atlas/README.md
> GRD-76413-linkUpdate

- filter-plugin/logstash-filter-cosmos-azure-guardium/README.md
- input-plugin/logstash-input-mongo-atlas/README.md
removed the note regarding plugin upload in v12 from mongo-atlas and cosmos
> Plug-ins readme update:

- filter-plugin/logstash-filter-pubsub-mysql-guardium/README.md
GRD-79814_added and updated multiple procedures.
> GRD-79814_Update README.md

- filter-plugin/logstash-filter-dynamodb-guardium/README.md
GRD-79871_Updated link to Configuring a universal connector in Guardium Insights topic.
> GRD-79871_Update README.md

- filter-plugin/logstash-filter-hdfs-guardium/README.md
GRD-79872_updated link to Configuring a universal connector in Guardium Insights topic.
> GRD-79872_Update README.md

- filter-plugin/logstash-filter-pubsub-postgresql-guardium/README.md
GRD-79879_updated link to postgresqlGooglePubsub.conf file in Sample Configurations
> GRD-79879_Update README.md

- filter-plugin/logstash-filter-pubsub-firestore-guardium/README.md
GRD-79878_updated link to firestore_pubsub_run.conf file.
> GRD-79878_Update README.md

- filter-plugin/logstash-filter-pubsub-firebase-realtime-guardium/README.md
GRD-79877_Updated link to firebase_with_pubsub.conf file.
> GRD-79877_Update README.md

- filter-plugin/logstash-filter-mysql-percona-guardium/README.md
GRD-79974_updated the procedure under Configuring Filebeat to push logs to Guardium section.
> GRD-79974_Update README.md

- filter-plugin/logstash-filter-snowflake-guardium/README.md
This fix is to publish the required fixed for,
- [GRD-81528](https://jira-ds.rtp.raleigh.ibm.com:8443/browse/GRD-81528)
> fix: GRD-81528 Updated the supporting version and the Environment part in the README.

- filter-plugin/logstash-filter-onPremPostgres-guardium/PostgresOverSyslogPackage/PostgresEDB/manifest.json
- filter-plugin/logstash-filter-onPremPostgres-guardium/PostgresOverSyslogPackage/gi_templates.json
- filter-plugin/logstash-filter-yugabyte-guardium/YugabyteOverSyslogPackage/YugabyteDB/manifest.json
- filter-plugin/logstash-filter-yugabyte-guardium/YugabyteOverSyslogPackage/gi_templates.json
- filter-plugin/logstash-filter-yugabyte-guardium/YugabytedbOverFilebeatPackage/YugabyteDB/manifest.json
- filter-plugin/logstash-filter-yugabyte-guardium/YugabytedbOverFilebeatPackage/gi_templates.json
change URL to the readme in the external repo
> Yugabyte+PostgreSQL on GI:

- filter-plugin/logstash-filter-oua-guardium/README.md
Update support versions and prerequisite section.
> GRD-83364_Update README.md

- filter-plugin/logstash-filter-oua-guardium/README.md
Reverts IBM/universal-connectors#507 as p7015 is not yet released.
> Revert "GRD-83364_Update README.md"

- filter-plugin/logstash-filter-neptune-aws-guardium/README.md
> GRD-83627-ReadMeUpdate

- docs/general topics/Notes_for_UC_plug-in_developers.md
All suggested changes for this document handled in 519 PR.  Created 521 PR only with 1 commit.
> UCX-243[DevNotesUpdate]

- common/src/main/java/com/ibm/guardium/universalconnector/commons/structures/Record.java
Update the commons code to add support for recordsAffected parameter in GuardRecord
> GRD-80022: Added recordsAffected attribute to uc-commons

- filter-plugin/logstash-filter-mssql-guardium/MssqlOverJdbcPackage/GCPMSSQL_README.md
Removed Guardium Insights SaaS: 1.0.
> GRD-83426_Update GCPMSSQL_README.md

- filter-plugin/logstash-filter-oua-guardium/README.md
> GRD-83364 - Update OUA README.md

- filter-plugin/logstash-filter-oua-guardium/README.md
> Update OUA readme.

- filter-plugin/logstash-filter-mongodb-guardium/README.md
GRD-78729 - Update MongoDB README.md
> Update MongoDB README.md

- filter-plugin/logstash-filter-mongodb-guardium/src/main/java/com/ibm/guardium/mongodb/AType.java
- filter-plugin/logstash-filter-mongodb-guardium/src/main/java/com/ibm/guardium/mongodb/MongodbGuardiumFilter.java
- filter-plugin/logstash-filter-mongodb-guardium/src/main/java/com/ibm/guardium/mongodb/ParserFactory.java
- filter-plugin/logstash-filter-mongodb-guardium/src/main/java/com/ibm/guardium/mongodb/parsersbytype/LoginParser.java
- filter-plugin/logstash-filter-mongodb-guardium/src/test/java/com/ibm/guardium/mongodb/parsers/LoginParserTest.java
Fixes:
- [GRD-82253](https://jira-ds.rtp.raleigh.ibm.com:8443/browse/GRD-82253)
> fix: GRD-82253 Releasing the code fixes to handle logout events for mongo

- filter-plugin/logstash-filter-azure-postgresql-guardium/AzurePostgresqlOverAzureEventHub/azurepostgresql/filter.conf
- filter-plugin/logstash-filter-azure-postgresql-guardium/README.md
- filter-plugin/logstash-filter-azure-postgresql-guardium/azurepostgresql.conf
- filter-plugin/logstash-filter-azure-postgresql-guardium/filter-test-generator.conf
- filter-plugin/logstash-filter-azure-postgresql-guardium/src/main/java/com/ibm/guardium/azurepostgresql/Parser.java
- filter-plugin/logstash-filter-azure-postgresql-guardium/src/test/java/com/ibm/guardium/azurepostgresql/ParserTest.java
1. Updating conf
2. Updating ReadMe
3. Updating source code and zip
> [GRD-80961,GRD-80162 and GRD-63127] Azure Postgres Publish new fixes

- docs/Guardium Data Protection/kafka_uc_integration.md
Updated the Kakfa cluster doc to describe new Kafka cluster management UI. **DO NOT MERGE**
> GRD-81665_Updated Kafka Cluster Doc

- filter-plugin/logstash-filter-snowflake-guardium/README.md
- filter-plugin/logstash-filter-snowflake-guardium/snowflakeJDBC.conf
Adding two optional parameter CLIENT_SESSION_KEEP_ALIVE=true&CLIENT_SESSION_KEEP_ALIVE_HEARTBEAT_FREQUENCY=60.
> Submit changes for GRD-87763.

- common/src/main/java/com/ibm/guardium/universalconnector/commons/custom_parsing/CustomParser.java
- common/src/main/java/com/ibm/guardium/universalconnector/commons/custom_parsing/SqlParser.java
- common/src/test/java/com/ibm/guardium/universalconnector/commons/custom_parsing/CustomParserTest.java
We need to add a support for Java parsing in case users want to add their own sql statement parsing
> INS-49969: Fixing some edge cases with the Custom Parser

- filter-plugin/logstash-filter-onPremPostgres-guardium/README.md
> Submit changes for GRD-90600.

- .github/CODEOWNERS
submit changes to add id in codeowner.
> submit changes to add id in codeowner.

- filter-plugin/logstash-filter-aurora-mysql-guardium/AuroraMysqlOverCloudwatchPackage/AuroraMysql/filter.conf
- filter-plugin/logstash-filter-aurora-mysql-guardium/auroraMysqlCloudwatch.conf
- filter-plugin/logstash-filter-aurora-mysql-guardium/auroraSQL-test-genertor.conf
> Submit changes for GRD-90012.

- gdp-packages/profile/CassandraOverFilebeatProfile/filter/filter.conf
- gdp-packages/profile/CassandraOverFilebeatProfile/filter/manifest.json
- gdp-packages/profile/CassandraOverFilebeatProfile/package.json
- gdp-packages/profile/CouchbasedbOverFilebeatProfile/filter/filter.conf
- gdp-packages/profile/CouchbasedbOverFilebeatProfile/filter/manifest.json
- gdp-packages/profile/CouchbasedbOverFilebeatProfile/package.json
- gdp-packages/profile/CouchdbOverFilebeatProfile/filter/filter.conf
- gdp-packages/profile/CouchdbOverFilebeatProfile/filter/manifest.json
- gdp-packages/profile/CouchdbOverFilebeatProfile/package.json
- gdp-packages/profile/GreenplumdbOverFilebeatProfile/filter/filter.conf
- gdp-packages/profile/GreenplumdbOverFilebeatProfile/filter/manifest.json
- gdp-packages/profile/GreenplumdbOverFilebeatProfile/package.json
- gdp-packages/profile/MariaDBOverFilebeatProfile/filter/filter.conf
- gdp-packages/profile/MariaDBOverFilebeatProfile/filter/manifest.json
- gdp-packages/profile/MariaDBOverFilebeatProfile/package.json
- gdp-packages/profile/MysqlPerconaOverFilebeatProfile/filter/filter.conf
- gdp-packages/profile/MysqlPerconaOverFilebeatProfile/filter/manifest.json
- gdp-packages/profile/MysqlPerconaOverFilebeatProfile/package.json
- gdp-packages/profile/NeodbOverFilebeatProfile/filter/filter.conf
- gdp-packages/profile/NeodbOverFilebeatProfile/filter/manifest.json
- gdp-packages/profile/NeodbOverFilebeatProfile/package.json
- gdp-packages/profile/PostgresOverFilebeatProfile/filter/filter.conf
- gdp-packages/profile/PostgresOverFilebeatProfile/filter/manifest.json
- gdp-packages/profile/PostgresOverFilebeatProfile/package.json
NeodbOverFilebeatProfile
MariaDBOverFilebeatProfile
GreenplumdbOverFilebeatProfile
CassandraOverFilebeatProfile
CouchbasedbOverFilebeatProfile
CouchdbOverFilebeatProfile
PostgresOverFilebeatProfile
MysqlPerconaOverFilebeatProfile
> GRD-93340[CM Management: Publish Filebeat plugins]

- filter-plugin/logstash-filter-pubsub-apachesolr-guardium/gi-pubsub-apachsolr-package/gi_templates.json
- filter-plugin/logstash-filter-pubsub-bigtable-guardium/gi-pubsub-bigtable-package/gi_templates.json
- filter-plugin/logstash-filter-pubsub-mysql-guardium/gi-pubsub-mysql-package/gi_templates.json
PubSub MySQL - Connection tiles are missing
> INS-53229: fixing the gi_templates for pubsub

- filter-plugin/logstash-filter-mssql-guardium/MssqlOnPremOverJdbcPackage/MssqlOverJdbcPackage/filter.conf
Placing old filter for MSSQL onPrem which is done for INS-49982
> INS-53024-MSSQL Filter Update

- common/build.gradle
- common/src/main/java/com/ibm/guardium/universalconnector/commons/custom_parsing/CustomParser.java
- common/src/main/java/com/ibm/guardium/universalconnector/commons/custom_parsing/ParserFactory.java
- common/src/main/java/com/ibm/guardium/universalconnector/commons/custom_parsing/SqlParser.java
- common/src/main/java/com/ibm/guardium/universalconnector/commons/custom_parsing/excepton/InvalidConfigurationException.java
- common/src/main/java/com/ibm/guardium/universalconnector/commons/custom_parsing/parsers/IParser.java
- common/src/main/java/com/ibm/guardium/universalconnector/commons/custom_parsing/parsers/JsonParser.java
- common/src/main/java/com/ibm/guardium/universalconnector/commons/custom_parsing/parsers/LeefParser.java
- common/src/main/java/com/ibm/guardium/universalconnector/commons/custom_parsing/parsers/RegexParser.java
- common/src/main/java/com/ibm/guardium/universalconnector/commons/custom_parsing/parsers/json_parser/JsonUtil.java
- common/src/test/java/com/ibm/guardium/universalconnector/commons/custom_parsing/CustomParserTest.java
- common/src/test/java/com/ibm/guardium/universalconnector/commons/custom_parsing/parsers/JsonParserTest.java
- common/src/test/java/com/ibm/guardium/universalconnector/commons/custom_parsing/parsers/LeefParserTest.java
- common/src/test/resources/config2.json
- common/src/test/resources/jsonConfig.json
[UC Editor] adding JSON/Leef custom parser
> INS-49047: Adding JSON/Leef parser

- filter-plugin/logstash-filter-mssql-guardium/MssqlOverJdbcPackage/AWSMSSQL_README.md
- filter-plugin/logstash-filter-mssql-guardium/MssqlOverJdbcPackage/ONPREMMSSQL_README.md
- filter-plugin/logstash-filter-mysql-aws-guardium/README.md
- filter-plugin/logstash-filter-mysql-guardium/README.md
- filter-plugin/logstash-filter-oua-guardium/OuaOverConnectJdbcReadme.md
- filter-plugin/logstash-filter-oua-guardium/OuaOverPipeReadme.md
- filter-plugin/logstash-filter-pubsub-mysql-guardium/README.md
- filter-plugin/logstash-filter-saphana-guardium/README.md
Updated first bullet point in Before you begin section.
> GRD-94333 Update READMEs

- build/verifiedThirdParties.txt
Updating snowflake driver to 3.23.0
> INS-54014: updating snowflake driver to 3.23.0

- filter-plugin/logstash-filter-cassandra-guardium/README.md
Review documentation on Cassandra
> GRD-90703: Review documentation on Cassandra

- common/src/main/java/com/ibm/guardium/universalconnector/commons/custom_parsing/CustomParser.java
- common/src/test/java/com/ibm/guardium/universalconnector/commons/custom_parsing/CustomParserTest.java
[UC Editor] Complete the package that we generate: updating the Custom parser based on the latest doc we got from Lions
> INS-54791: updating the Custom parser

- gdp-packages/profile/JDBCKafkaConnectProfile/kafka_connect.json
change to value converter to StringConverter
> GRD-96033: fix missing value.converter StringConverter

- common/src/main/java/com/ibm/guardium/universalconnector/commons/custom_parsing/CustomParser.java
- common/src/main/java/com/ibm/guardium/universalconnector/commons/custom_parsing/PropertyConstant.java
Adding a universal connector for Trino on Hive
> GRD-94172: Improving some stuff in common parser

- filter-plugin/logstash-filter-cosmos-azure-guardium/README.md
Review the documentation for Cosmos
> GRD-90734 review the readme

- filter-plugin/logstash-filter-couchdb-guardium/README.md
Review the documentation for Couchdb
> GRD-90705: Review the readme

- filter-plugin/logstash-filter-aurora-mysql-guardium/README.md
- filter-plugin/logstash-filter-documentdb-aws-guardium/README.md
- filter-plugin/logstash-filter-dynamodb-guardium/DynamodbOverCloudwatch/README.md
- filter-plugin/logstash-filter-mariadb-aws-guardium/README.md
- filter-plugin/logstash-filter-mysql-aws-guardium/README.md
- filter-plugin/logstash-filter-neptune-aws-guardium/README.md
- filter-plugin/logstash-filter-postgres-guardium/AuroraPostgres_README.md
- filter-plugin/logstash-filter-postgres-guardium/AwsPostgres_README.md
- filter-plugin/logstash-filter-redshift-aws-guardium/README.md
- filter-plugin/logstash-filter-s3-guardium/README.md
> GRD-93619 update 12.0 GDP version for cloudwatch

- filter-plugin/logstash-filter-documentdb-aws-guardium/README.md
Review the documentation for DocumentDB
> GRD-90706:  Review the readme

- common/src/main/java/com/ibm/guardium/universalconnector/commons/custom_parsing/CustomParser.java
- common/src/test/java/com/ibm/guardium/universalconnector/commons/custom_parsing/CustomParserTest.java
Fix the issue in custom parser
> GRD-98644: avoid converting empty space to int

- input-plugin/logstash-input-cloudwatch-logs/README.md
- input-plugin/logstash-input-cloudwatch-logs/SettingsForRoleArn.md
Synchronizing Cloudwatch logs Input Plugin
> GRD-93754: Cloudwatch logs Input Plugin

- common/src/main/java/com/ibm/guardium/universalconnector/commons/custom_parsing/CustomParser.java
- common/src/test/java/com/ibm/guardium/universalconnector/commons/custom_parsing/CustomParserTest.java
There was a build issure resulting from ambiguous Record
> GRD-99555: Fixing the build issue

- filter-plugin/logstash-filter-oua-guardium/OuaOverConnectJdbcReadme.md
Added limitations in the Configuring UC on GDP section
> GRD-98935 - Update OuaOverConnectJdbcReadme.md

- common/src/main/java/com/ibm/guardium/universalconnector/commons/custom_parsing/CustomParser.java
- common/src/test/java/com/ibm/guardium/universalconnector/commons/custom_parsing/CustomParserTest.java
> GRD-101664: Fix issues on Capella

- filter-plugin/logstash-filter-azure-postgresql-guardium/README.md
- Modify readme file to increase the throughput units in Azure EventHub to prevent data loss for PostgreSQL
> [master] GRD-93886 : Azure Postgres over EventHub UC Performance - Data Loss and slow processing observed in Performance Tests

- build/defaultOfflinePackagePlugins.txt
- filter-plugin/logstash-filter-trino-guardium/README.md
https://ibm-datasecurity.atlassian.net/browse/GRD-105254
> GRD-105254 Fix wrong directory name causing public repo failure - logstash-filter-trino_guardium_plugin_filter

- filter-plugin/logstash-filter-oua-guardium/OuaOverConnectJdbcReadme.md
- filter-plugin/logstash-filter-oua-guardium/OuaOverPipeReadme.md
> GRD-104738: OuaOverConnectJdbcReadme link updates

- filter-plugin/logstash-filter-databricks-guardium/src/main/java/com/ibm/guardium/databricks/Parser.java
- filter-plugin/logstash-filter-databricks-guardium/src/test/java/com/ibm/guardium/databricks/ParserTest.java
replace service name with N.A.
> GRD-107009

- filter-plugin/logstash-filter-oua-guardium/OuaOverPipeReadme.md
Adds note for [GRD-108594](https://ibm-datasecurity.atlassian.net/browse/GRD-108594).
> GRD-108594: TCP protocol for Oracle Autonomous Database

- filter-plugin/logstash-filter-neo4j-guardium/src/main/java/com/ibm/guardium/neodb/Parser.java
- filter-plugin/logstash-filter-neo4j-guardium/src/test/java/com/ibm/guardium/neodb/ParserTest.java
Jira Ticket: https://ibm-datasecurity.atlassian.net/browse/GRD-106525
- Add unit test for empty hash map 
- Remove static modifier from variables 
Tested on MU - 
```
[root@sysqa-uc-thor1 scripts]# ./NEO4J_create_and_drop_loop.sh
...
Creating variable VARIABLE_jasminetestagain_43
Deleting variable VARIABLE_jasminetestagain_43
Creating variable VARIABLE_jasminetestagain_44
Deleting variable VARIABLE_jasminetestagain_44
Creating variable VARIABLE_jasminetestagain_45
Deleting variable VARIABLE_jasminetestagain_45
Creating variable VARIABLE_jasminetestagain_46
Deleting variable VARIABLE_jasminetestagain_46
Creating variable VARIABLE_jasminetestagain_47
Deleting variable VARIABLE_jasminetestagain_47
Creating variable VARIABLE_jasminetestagain_48
Deleting variable VARIABLE_jasminetestagain_48 …
```
> GRD-106525:[UC 12.2 Neo4j]: Errors observed in logstash after executing traffic for Neo4j by running the script.
